require("abilities");
require("launchpadadamantite");
require("hyperwall");
require("ejectors");
require("odium-mine");
require("content2/blocks/crafting");
require("content2/blocks/defense");
require("content2/blocks/effect");
require("content2/blocks/distribution");
require("content2/blocks/liquid");
require("content2/blocks/power");
require("content2/blocks/production");
require("content2/blocks/turrets");
require("content2/blocks/units");
require("content2/items");
require("content2/bullets");
require("content2/units");
require("content2/weather");
require("content2/statusEffects");

require("effects");
require("techTree")
